### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by wuqiang3424** [jumpserver/helm#23]
执行这条安装命令之后等一会儿会有以下报错，然后就停止运行了，helm install jumpserver1 ./
Error: failed pre-install: timed out waiting for the condition

**Comment by wojiushixiaobai** [comment]
看 job 报什么错，错误日志发上来

**Comment by wuqiang3424** [comment]
![Uploading image.png…]()
我只能查到这个

**Comment by wuqiang3424** [comment]
https://imgtu.com/i/4gcX60
[root@k8s-jumpserver-master-1 helm]# helm status jumpserver
NAME: jumpserver
LAST DEPLOYED: Mon Sep 27 10:39:09 2021
NAMESPACE: default
STATUS: failed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Jumpserver URL by running these commands:
  http://test.jumpserver.org

2. Access the Jumpserver SSH server by running these commands:

**Comment by wojiushixiaobai** [comment]
kubectl get job 看看错误
